name: Actividades Extracurriculares 
run-name: ${{github.actor}} - Actividades
on: [push]
jobs:
  actividades:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requiriments.txt

      - name: Run script
        run: python main.py

      - name: wait
        run: sleep 2m
        shell: bash
